include_guard(GLOBAL)

set(_III_MISSION_KNOWN_PROFILES hil opti_track real sim)
set(_III_MISSION_CLASSIFICATIONS production experimental test legacy)
set(_III_MISSION_STATUSES active deprecated)

function(iii_register_mission)
  set(options)
  set(one_value_args ID SPECIFICATION CLASSIFICATION STATUS)
  set(multi_value_args PROFILES DEFAULT_FOR)
  cmake_parse_arguments(MISSION "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

  foreach(required ID SPECIFICATION CLASSIFICATION)
    if(NOT MISSION_${required})
      message(FATAL_ERROR "iii_register_mission requires ${required}")
    endif()
  endforeach()
  if(MISSION_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "iii_register_mission(${MISSION_ID}) has unknown arguments: ${MISSION_UNPARSED_ARGUMENTS}")
  endif()
  if(NOT MISSION_ID MATCHES "^[a-z0-9]([a-z0-9.-]*[a-z0-9])?$")
    message(FATAL_ERROR "iii_register_mission ID is invalid: ${MISSION_ID}")
  endif()
  if(NOT MISSION_PROFILES)
    message(FATAL_ERROR "iii_register_mission(${MISSION_ID}) requires PROFILES")
  endif()
  if(NOT MISSION_STATUS)
    set(MISSION_STATUS active)
  endif()
  if(NOT MISSION_CLASSIFICATION IN_LIST _III_MISSION_CLASSIFICATIONS)
    message(FATAL_ERROR "iii_register_mission(${MISSION_ID}) has unknown CLASSIFICATION ${MISSION_CLASSIFICATION}")
  endif()
  if(NOT MISSION_STATUS IN_LIST _III_MISSION_STATUSES)
    message(FATAL_ERROR "iii_register_mission(${MISSION_ID}) has unknown STATUS ${MISSION_STATUS}")
  endif()
  foreach(profile IN LISTS MISSION_PROFILES MISSION_DEFAULT_FOR)
    if(NOT profile IN_LIST _III_MISSION_KNOWN_PROFILES)
      message(FATAL_ERROR "iii_register_mission(${MISSION_ID}) has unknown profile ${profile}")
    endif()
  endforeach()
  foreach(profile IN LISTS MISSION_DEFAULT_FOR)
    if(NOT profile IN_LIST MISSION_PROFILES)
      message(FATAL_ERROR "iii_register_mission(${MISSION_ID}) is default for disallowed profile ${profile}")
    endif()
  endforeach()

  get_property(ids GLOBAL PROPERTY III_MISSION_REGISTRATION_IDS)
  if(MISSION_ID IN_LIST ids)
    message(FATAL_ERROR "duplicate iii_register_mission ID: ${MISSION_ID}")
  endif()
  get_filename_component(specification "${MISSION_SPECIFICATION}" ABSOLUTE BASE_DIR "${PROJECT_SOURCE_DIR}")
  if(NOT EXISTS "${specification}" OR IS_DIRECTORY "${specification}")
    message(FATAL_ERROR "iii_register_mission(${MISSION_ID}) specification is missing: ${specification}")
  endif()
  get_filename_component(specification_real "${specification}" REALPATH)
  get_filename_component(source_real "${PROJECT_SOURCE_DIR}" REALPATH)
  file(RELATIVE_PATH specification_relative "${source_real}" "${specification_real}")
  if(specification_relative MATCHES "^\\.\\.(/|$)" OR IS_ABSOLUTE "${specification_relative}")
    message(FATAL_ERROR "iii_register_mission(${MISSION_ID}) specification escapes the package source")
  endif()

  list(SORT MISSION_PROFILES)
  list(SORT MISSION_DEFAULT_FOR)
  list(JOIN MISSION_PROFILES "," profiles_csv)
  list(JOIN MISSION_DEFAULT_FOR "," defaults_csv)
  set(record "${MISSION_ID}\t${specification_real}\t${MISSION_CLASSIFICATION}\t${MISSION_STATUS}\t${profiles_csv}\t${defaults_csv}")
  set_property(GLOBAL APPEND PROPERTY III_MISSION_REGISTRATION_IDS "${MISSION_ID}")
  set_property(GLOBAL APPEND PROPERTY III_MISSION_REGISTRATION_RECORDS "${record}")
  set_property(GLOBAL APPEND PROPERTY III_MISSION_REGISTRATION_SOURCES "${specification_real}")
endfunction()

function(iii_write_mission_registrations output)
  get_property(records GLOBAL PROPERTY III_MISSION_REGISTRATION_RECORDS)
  if(NOT records)
    message(FATAL_ERROR "no missions were declared with iii_register_mission")
  endif()
  list(SORT records)
  set(content "")
  foreach(record IN LISTS records)
    string(APPEND content "${record}\n")
  endforeach()
  file(WRITE "${output}" "${content}")
endfunction()
